version: 2

project_name: open-ve

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./go/cmd/open-ve
    binary: open-ve
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: shibukazu
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    description: "Open-VE: A powerful solution that simplifies the management of validation rules, ensuring consistent validation across all layers, including frontend, BFF, and microservices, through a single, simple API."
    dependencies:
      - name: go
        type: optional

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"
