services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
    restart: unless-stopped
  server:
    build:
      context: .
    container_name: server
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - default
    depends_on:
      - redis
  apidocs:
    image: swaggerapi/swagger-ui
    container_name: apidocs
    environment:
      - SWAGGER_JSON=/openapi/openapi.swagger.json
      - BASE_URL=/docs
    volumes:
      - ./openapi:/openapi
    restart: unless-stopped
    ports:
      - "18080:8080"

volumes:
  redis-data:

networks:
  default:
    driver: bridge
