services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
    restart: unless-stopped
  master-node:
    build:
      context: .
    container_name: master-node
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - default
    depends_on:
      - redis
    environment:
      - OPEN-VE_MODE=master
      - OPEN-VE_HTTP_PORT=
      - OPEN-VE_HTTP_CORS_ALLOWED_ORIGINS=
      - OPEN-VE_HTTP_CORS_ALLOWED_HEADERS=
      - OPEN-VE_HTTP_TLS_ENABLED=
      - OPEN-VE_HTTP_TLS_CERT_PATH=
      - OPEN-VE_HTTP_TLS_KEY_PATH=
      - OPEN-VE_GRPC_PORT=
      - OPEN-VE_GRPC_TLS_ENABLED=
      - OPEN-VE_GRPC_TLS_CERT_PATH=
      - OPEN-VE_GRPC_TLS_KEY_PATH=
      - OPEN-VE_STORE_ENGINE=redis
      - OPEN-VE_STORE_REDIS_ADDR=
      - OPEN-VE_STORE_REDIS_PASSWORD=
      - OPEN-VE_STORE_REDIS_DB=
      - OPEN-VE_STORE_REDIS_POOL_SIZE=
      - OPEN-VE_LOG_LEVEL=
  slave-node:
    build:
      context: .
    container_name: slave-node
    ports:
      - "8090:8080"
      - "9010:9000"
    networks:
      - default
    depends_on:
      - redis
      - master-node
    environment:
      - OPEN-VE_MODE=slave
      - OPEN-VE_SLAVE_ID=slave-node
      - OPEN-VE_SLAVE_SLAVE_HTTP_ADDR=http://slave-node:8080
      - OPEN-VE_SLAVE_MASTER_HTTP_ADDR=http://master-node:8080
      - OPEN-VE_SLAVE_MASTER_TLS_ENABLED=
      - OPEN-VE_HTTP_PORT=
      - OPEN-VE_HTTP_CORS_ALLOWED_ORIGINS=
      - OPEN-VE_HTTP_CORS_ALLOWED_HEADERS=
      - OPEN-VE_HTTP_TLS_ENABLED=
      - OPEN-VE_HTTP_TLS_CERT_PATH=
      - OPEN-VE_HTTP_TLS_KEY_PATH=
      - OPEN-VE_GRPC_PORT=
      - OPEN-VE_GRPC_TLS_ENABLED=
      - OPEN-VE_GRPC_TLS_CERT_PATH=
      - OPEN-VE_GRPC_TLS_KEY_PATH=
      - OPEN-VE_STORE_ENGINE=redis
      - OPEN-VE_STORE_REDIS_ADDR=
      - OPEN-VE_STORE_REDIS_PASSWORD=
      - OPEN-VE_STORE_REDIS_DB=
      - OPEN-VE_STORE_REDIS_POOL_SIZE=
      - OPEN-VE_LOG_LEVEL=
  apidocs:
    image: swaggerapi/swagger-ui
    container_name: apidocs
    environment:
      - SWAGGER_JSON=/openapi/openapi.swagger.json
      - BASE_URL=/docs
    volumes:
      - ./openapi:/openapi
    restart: unless-stopped
    ports:
      - "18080:8080"

volumes:
  redis-data:

networks:
  default:
    driver: bridge
