services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
    restart: unless-stopped
  server:
    build:
      context: .
    container_name: server
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - default
    depends_on:
      - redis
    environment:
      - OPEN-VE_HTTP_ADDR=
      - OPEN-VE_HTTP_CORS_ALLOWED_ORIGINS=
      - OPEN-VE_HTTP_CORS_ALLOWED_HEADERS=
      - OPEN-VE_HTTP_TLS_ENABLED=
      - OPEN-VE_HTTP_TLS_CERT_PATH=
      - OPEN-VE_HTTP_TLS_KEY_PATH=
      - OPEN-VE_GRPC_ADDR=
      - OPEN-VE_GRPC_TLS_ENABLED=
      - OPEN-VE_GRPC_TLS_CERT_PATH=
      - OPEN-VE_GRPC_TLS_KEY_PATH=
      - OPEN-VE_STORE_ENGINE=
      - OPEN-VE_STORE_REDIS_ADDR=
      - OPEN-VE_STORE_REDIS_PASSWORD=
      - OPEN-VE_STORE_REDIS_DB=
      - OPEN-VE_STORE_REDIS_POOL_SIZE=
      - OPEN-VE_LOG_LEVEL=
  apidocs:
    image: swaggerapi/swagger-ui
    container_name: apidocs
    environment:
      - SWAGGER_JSON=/openapi/openapi.swagger.json
      - BASE_URL=/docs
    volumes:
      - ./openapi:/openapi
    restart: unless-stopped
    ports:
      - "18080:8080"

volumes:
  redis-data:

networks:
  default:
    driver: bridge
