services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    restart: unless-stopped
  apidocs:
    image: swaggerapi/swagger-ui
    container_name: apidocs
    environment:
      - SWAGGER_JSON=/openapi/openapi.swagger.json
      - BASE_URL=/docs
    volumes:
      - ./openapi:/openapi
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
