name: Code Static Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1.30.1
        with:
          version: "1.28.1"
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - name: Run Buf Lint
        run: buf lint
      - name: Run Buf format
        run: buf format -d --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
