name: Code Static Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - name: Run Buf Lint
        run: buf lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
