name: Code Gen Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1.30.1
        with:
          version: "1.28.1"
      - uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
      - run: buf format -d --exit-code
      - name: "Generate Codes"
        run: |
          buf generate
          git diff --text --exit-code go/proto/**/*.go openapi/**/*.json
