name: Code Gen Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.2
      - name: Install Deps
        run: |
          go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
          go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: Run Buf Generate
        run: buf generate
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
          echo "Generated code is not up to date. Please run 'buf generate' and commit the changes."
          git diff
          exit 1
          else
          echo "Generated code is up to date."
          fi
